baseURL = "https://ywallet.app/"
#baseURL = "/"
title = "YWallet"

theme = "hugo-theme-learn"

[params]
themeVariant = "blue"
showVisitedLinks = true
disableLandingPageButton = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[markup.goldmark.renderer]    
unsafe = true
