name: Build and Release MacOS Universal

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build_rust:
    runs-on: macos-12
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: download params
        run: ./build-scripts/mac/download-params.sh

      - name: build
        run: ./build-scripts/mac/build-${{ matrix.arch }}.sh

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.arch }}
          path: target/${{ matrix.arch }}-apple-darwin/release

  build_flutter:
    runs-on: macos-12
    needs: build_rust
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: env
        run: |
          cat build.env >> $GITHUB_ENV
          echo $PWD/flutter/bin >> $GITHUB_PATH

      - uses: actions/download-artifact@v3
        with:
          name: x86_64
          path: target/x86_64-apple-darwin/release

      - uses: actions/download-artifact@v3
        with:
          name: aarch64
          path: target/aarch64-apple-darwin/release

      - name: build flutter
        run: ./build-scripts/mac/build-flutter.sh "$FLUTTER_VERSION"

      - name: codesign
        env:
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
          MACOS_CI_KEYCHAIN_PWD: ${{ secrets.MACOS_CI_KEYCHAIN_PWD }}
          MACOS_CERTIFICATE_ID: ${{ secrets.MACOS_CERTIFICATE_ID }}
        run: ./build-scripts/mac/codesign-mac.sh "$MACOS_CERTIFICATE" "$MACOS_CERTIFICATE_PWD" "$MACOS_CI_KEYCHAIN_PWD" "$MACOS_CERTIFICATE_ID"

      - name: notarize
        env:
          MACOS_NOTARIZATION_APPLE_ID: ${{ secrets.MACOS_NOTARIZATION_APPLE_ID }}
          MACOS_NOTARIZATION_TEAM_ID: ${{ secrets.MACOS_NOTARIZATION_TEAM_ID }}
          MACOS_NOTARIZATION_PWD: ${{ secrets.MACOS_NOTARIZATION_PWD }}
        run: ./build-scripts/mac/notarize-mac.sh "$MACOS_NOTARIZATION_APPLE_ID" "$MACOS_NOTARIZATION_TEAM_ID" "$MACOS_NOTARIZATION_PWD"

      - name: package
        run: ./build-scripts/mac/pkg-mac.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            ./ywallet-universal.dmg
